### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Dissectum** [MaaXYZ/MBA#1]
# TODO List

- [ ] feat: 国服次数选择适配（等悬赏通缉出来后）
- [ ] fix: Task 异常退出，却返回 Success 的问题
- [ ] fix: 咖啡厅感叹号是个动画
- [ ] fix: 咖啡厅好感识别改成颜色识别或其他识别方式，原因：模版匹配遇到纯色傻掉
- [ ] feat: 添加 ResourceReviewer Test Action
- [ ] fix: 连接实体机

## v0.2.1
- [ ] fix: 反复进入问题，修改后 Goto 的 next 顺序：[ "Flag"（是否在页面）, "Sub_Goto"（是否在父页面）, "Check"（确认票数啥的）, "Click"（在父页面中点击） ]，Click 的 next: [ "Notify", "Wait", "Flag"（是否在页面） ]

## v0.2.0
- [x] fix: StartUp 退太多
- [x] chore: 升级 MaaToolkit
- [x] chore: 调整更新提醒
- [x] fix: TOUCH
- [x] fix: 退出按两次
- [x] fix: Startup 先直接 StartApp
- [x] fix: 语言和服务器相同的问题（原因为解析成 None）
- [x] fix: 咖啡厅收起左下角
- [x] ~~fix: Sweep 完成后点击Close（复现失败，可能无意间修了）~~
- [x] fix: 国服BaseDefense ItemRetrieval 都执行了一次
- [x] fix: 繁中悬赏通缉和学园交流会精细识别

## v0.1.1
- [x] fix: 从可执行文件运行完成后未暂停的问题
- [x] fix: PublishTrimmed 的可执行文件，不能读取配置文件的问题
- [x] chore: 日志去除 User Dir 记录（因为 fw 已经记录了）
- [x] chore: 去除 Config Doc 中现在不可用的任务
- [x] feat: 添加没有自包含的 win-x64 Release
- [x] feat: 添加更新提示
- [x] feat: 添加 ChangeLog  提示（因为随时可能对 Config 破坏性更新）

# Won't fix List
- 异形屏：UI 有过拉伸
